#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forchina_fn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    jdbc:mysql://localhost:3306/lovewhf?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#mybatis mapper 路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 控制台打印当前执行的sql信息
logging:
  level:
    com.fn.dao.mapper.*: debug # 这是mapper包路径 F:\prodemo\mybatis_generater\src\main\java\com\fn\dao\mapper